add SOA support
projectdiscovery/retryabledns pull request #127
Opened 2023-05-17 13:31 UTC by hachh

Currently retryabledns does not support DNS zone queries, the SOA query gives the nameservers but no zone information.
This modification provides information about the DNS zone.

2023-05-18 04:22 UTC, Mzack9999 requested changes
@hachh Thanks a lot for this PR. I tried implementing a couple of improvements but unfortunately there is no push permission on the fork, so I left them as comments.
Could you also change the test `client_test.go` as follows:

```go
func TestQueryMultiple(t *testing.T) {
	client, _ := New([]string{"8.8.8.8:53", "1.1.1.1:53"}, 5)

	// Test various query types
	d, err := client.QueryMultiple("scanme.sh", []uint16{
		dns.TypeA,
		dns.TypeAAAA,
		dns.TypeSOA,
	})
	require.Nil(t, err)

	// From current dig result
	require.True(t, len(d.A) > 0)
	require.True(t, len(d.AAAA) > 0)
	require.True(t, len(d.SOA) > 0)
	require.NotZero(t, d.TTL)
}
```

Thanks!

2023-05-18 04:22 UTC, Mzack9999 commented on client.go
> +	SOA            SOA        `json:"soa,omitempty"`
According to [rfc1034](https://datatracker.ietf.org/doc/html/rfc1034), there should be only one SOA answer record, but the library tends to tolerate non-compliant servers. So I'd suggest changing it to:

```go
type DNSData struct {
...
  SOA []SOA
...
}
```

2023-05-18 04:22 UTC, Mzack9999 commented on client.go
> +			d.SOA = SOA{
After it changes to slice, this should be:
```go
d.SOA = append(d.SOA, append(d.SOA, SOA{
...
}
```

2023-05-18 08:48 UTC, hachh commented
Hello @Mzack9999 

Thanks for your comments!
I've just updated the code to include your comments, I've also granted you write access to the fork repository if you want to push more changes.

2023-05-22 05:44 UTC, Mzack9999 approved these changes
lgtm!

2023-05-22 05:44 UTC, merged