updated go mod and adjusted stringsutil recent changes
projectdiscovery/retryabledns pull request #68
Opened 2022-08-02 19:34 UTC by LuitelSamikshya

2022-08-03 04:32 UTC, Mzack9999 requested changes

2022-08-03 04:32 UTC, Mzack9999 commented on hostsfile/hostsfile.go
>  		if strings.Contains(line, "#") {
I think we can replace this with:
```go
if idx := strings.Index(line, "#"); idx > 0 {
	line = line[:idx]
}
```

2022-08-03 15:05 UTC, LuitelSamikshya commented on hostsfile/hostsfile.go
>  		if strings.Contains(line, "#") {
Done.

2022-08-04 05:21 UTC, Mzack9999 approved these changes
LGTM - Follow up ticket at https://github.com/projectdiscovery/retryabledns/issues/69 related to increase test coverage

2022-08-04 11:29 UTC, ehsandeep approved these changes

2022-08-04 11:29 UTC, merged